# Generated by Django 5.0.4 on 2024-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number_version",
            field=models.IntegerField(default=1, verbose_name="Номер версии"),
        ),
    ]
