# Generated by Django 5.0.4 on 2024-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Blogging/", verbose_name="Картинки"
            ),
        ),
    ]
